### ISSUE TITLE
[10.0] sentry: Tests failing

### ISSUE THREAD

**Issue by obulkin** [OCA/server-tools#1096]
Two of the unit tests in the ``sentry`` module are currently failing, as can be seen here: https://travis-ci.org/OCA/server-tools/jobs/316634324. I've replicated this issue locally using the 10.0 branch and confirmed that it is not related to ``auth_totp``.

@lasley

**Comment by naglis** [comment]
I think this is due to the fact that the [`FIELDS` class attribute](https://github.com/OCA/server-tools/blob/3bb12bd80cb9c6409521eb54025d12da9aa210cc/sentry/logutils.py#L104) has been [renamed to `KEYS`](https://github.com/getsentry/raven-python/blob/9f56a51ebfd67ee094d47a93fb049fe8b40ac0a4/raven/processors.py#L154) in [raven 6.4.0](https://github.com/getsentry/raven-python/releases/tag/6.4.0).

I think it might be enough to add a `KEYS` class attribute on [`SanitizeOdooCookiesProcessor`](https://github.com/OCA/server-tools/blob/3bb12bd80cb9c6409521eb54025d12da9aa210cc/sentry/logutils.py#L97) pointing to `FIELDS` (to maintain backwards compatibility with older versions of Raven).

I will test it and hopefully make a fix tomorrow.

This should affect #1023 as well.

**Comment by naglis** [comment]
@pedrobaeza, OK to close?
