### ISSUE TITLE
12.0 auto_backup access denied list_db

### ISSUE THREAD

**Issue by jcarlosmontoya** [OCA/server-tools#1664]
Module does not work when list_db parameter is False

![image](https://user-images.githubusercontent.com/7680456/64592736-f3d26b80-d3ac-11e9-9268-95a256ce0a0a.png)

Odoo check this
![image](https://user-images.githubusercontent.com/7680456/64592860-38f69d80-d3ad-11e9-8fdf-fda391dbc8a8.png)

![image](https://user-images.githubusercontent.com/7680456/64592905-4a3faa00-d3ad-11e9-85d0-26eacfdd1298.png)

![image](https://user-images.githubusercontent.com/7680456/64593115-c33f0180-d3ad-11e9-959f-498693bdc908.png)

**Comment by OmniaGit** [comment]
In case of cloud database we always disable the list of it.
so in this case will be very useful having a field that allows to specifies if you want to backup a single database or all the database..

**Comment by mcerutti** [comment]
I'm having the same issue on v14. There's any update ?

**Comment by mathben** [comment]
**This is the reason**
Message :
[MERGE] forward port branch saas-15 up to 43eca3079e4

Author : 
Christophe Simonis

Time :
Commit #b29e053436b69223e25c49955006c910cd59316d

Date :
Mon Aug 06 05:32:12 EDT 2018

**Solution**
We can support to backup multiple database, this is what you want? Or we can disable this feature when no need it?
The reason is to not backup another database then yours when you share the machine.
