### ISSUE TITLE
[IMP][question] base_custom_info support for ranges and/or combinations

### ISSUE THREAD

**Issue by Rad0van** [OCA/server-tools#1934]
I am using base_custom_info, product_custom_info and website_sale_custom_info (WiP based on older unmerged PR - will create PR for that) to manage information about products. Now I came across few cases where I'd need:

- range (either of whole or decimal numbers) - i.e. some parameter is in the range from 100 to 350
- combination (either of whole or decimal numbers) - i.e. dimensions is combination of width, height, depth

Currently I am storing these as separate properties named similarly (i.e. some_parameter_min, some_parameter_max). It would be nice to have the option to manage them in more "clever" way. I see basically 2 options:

1. Extend current implementation to allow this. So the Property would be either plain/basic (current version), range or combination (where you'd define the number of dimensions). This would require more complicated storing of the content of the property, more complicated UI.
2. Create some meta-properties that would group normal properties to allow for at least displaying in a certain manner. This would not be that complicated implementation-wise - mainly those meta properties definition and handling.

I would welcome some feedback on this. @pedrobaeza, @Yajo, @etobella, @Tardo, @sergio-teruel, @carlosdauden or @rafaelbn would you care to comment please? Would you go this way or some other? Also - should I enhance existing module or attempt to create a module that depends on existing one?

**Comment by pedrobaeza** [comment]
I think you can add constraints in attributes in a generic way with a constraint expression in the base module, instead of max and min. With that, you have more flexibility, and max and min will be something similar like `value < 0 or value > 100` for constraining the possible values. Check an example of dynamic constraints in https://github.com/OCA/server-ux/blob/8f6a3e7d63a6f543fc15e8bb954a93e63e9a1581/chained_swapper/models/chained_swapper.py#L166

**Comment by Rad0van** [comment]
Hi,

I am not sure I explained it properly. Let me give you an example of what I 
considered a "range": combi machines used in professional kitchens have 
capacity of meals they can cook in a single batch. The usual values are 
something like "100-150", "200-300", ... So I wasn't looking for limiting the 
property value to a certain (dynamic) range but I was looking for a way to 
store this not as text but as 2 numbers and maybe use them in future for 
searching, comparison, etc. Not sure how the constraints you mention would 
play into this. I would be more inclined to use some regular expression to 
enforce a valid input.

The situation with dimensions is similar. I want to store values like 
"120x80x90", ...

But maybe I am just trying to overengineer this and right now don't have a 
clear use case of how I would use the info if I could access the individual 
numbers insted of a string representation of range/dimensions. Wanted to hear 
opinions of more skilled people on this.

Best regards

	Radovan

**Comment by pedrobaeza** [comment]
Well, my proposal is to split such range into different lines, so for 120x80x90, you have 3 lines, and each one has their constraints.

**Comment by Rad0van** [comment]
That's the way I do it now.

	Radovan

**Comment by yajo** [comment]
This seems solved, right?

**Comment by Rad0van** [comment]
> This seems solved, right?

Yeah - it was more inquiry about best design approach...

**Comment by ska-ibees** [comment]
@Rad0van how can we replicate behavior of many2many field? In my use case, I need to categories different products in a way that there are individual fields with multiple options and possibility to select mulitple values instead of single one.

For example, for each product:
1. Color options (Need multiple values for this single field)
2. Style options (Need multiple values for this single field)

My end goal is to show such options in a custom quote form where a lead can be generated and also to have a relation of these custom values with crm.lead model as well. 

BTW, Currently I have achieved this feature by adding few many2many fields on product.template. Problem I am facing is the growing number of product ids  to match with the selected product at client side . To handle this situation I am thinking of using template with certain combinations instead of applying everything directly on the product. This lead me to consider product_custom_info but not sure how to simulate many2many  behavior .




![image](https://user-images.githubusercontent.com/5569632/125659130-25066f5f-3558-48f6-ac26-5fed37a3f6d5.png)

**Comment by Rad0van** [comment]
Not sure I follow. You need a type of property, for which you can multiple values out of list? And these should be references to buy just strings but certain objects? I guess this could be done extending the types of properties.

It you just need to select from defined lust of values? That already is there - I think it's called choice.


> @Rad0van how can we replicate behavior of many2many field? In my use case, I need to categories different products in a way that there are individual fields with multiple options and possibility to select mulitple values instead of single one.
> 
> For example, for each product:
> 1. Color options (Need multiple values for this single field)
> 2. Style options (Need multiple values for this single field)
> 
> My end goal is to show such options in a custom quote form where a lead can be generated and also to have a relation of these custom values with crm.lead model as well. 
> 
> BTW, Currently I have achieved this feature by adding few many2many fields on product.template. Problem I am facing is the growing number of product ids  to match with the selected product at client side . To handle this situation I am thinking of using template with certain combinations instead of applying everything directly on the product. This lead me to consider product_custom_info but not sure how to simulate many2many  behavior .
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5569632/125659130-25066f5f-3558-48f6-ac26-5fed37a3f6d5.png)
>
