### ISSUE TITLE
Tracking all the modules using audit logs gives error

### ISSUE THREAD

**Issue by maddy518** [OCA/server-tools#270]
I want to track all the user operations irrespective of the module, whatever the module is. I selected object as 'ir.model' when defining the rule but it doesn't track anything in the logs.

Is there a way to handle this or needs to be fixed?

Regards,
Maddy.

**Comment by StefanRijnhart** [comment]
Not quite clear to me what you would like to do. By defining a rule on ir.model, it seems like you would want to track when a new model is added to the Odoo database layout (for instance, on module installation or update). If that is the case, you are out of luck because most operations on the ir_model table are executed through SQL and bypass the ORM hooks that are tracked using the _auditlog_ module.

Does that answer your question?

**Comment by sebalix** [comment]
I think that what @maddy518 wants is to track every user operations, without targeting a data model particularly.
At this time _auditlog_ is not able to do that, you need to create one rule by data model, but be careful as it can slow down your _Odoo_ instance, #357 should be needed to improve the global performance. Also there is the #169 PR which could help to configure a lot of rules at once (one by data model), but it needs some work to be integrated.

**Comment by pedrobaeza** [comment]
Answered, so I close.
