### ISSUE TITLE
[8.0][dead_mans_switch_client] Module crashes runbots

### ISSUE THREAD

**Issue by yajo** [OCA/server-tools#314]
I'm seeing more and more runbots with :x: because of this module. [This seems the offending line](https://github.com/OCA/server-tools/blob/8.0/dead_mans_switch_client/models/dead_mans_switch_client.py#L54). Any clue on how to fix it?

Example runbot: https://runbot.odoo-community.org/runbot/build/3137787

CC @hbrunn.

**Comment by hbrunn** [comment]
make a PR to log a warning instead of an error. Or better (but not simple to do) make a PR for runbot to ignore some error logs

**Comment by yajo** [comment]
I can see this fails because no `dead_mans_switch_client.url` parameter is present. What about creating demo data for it pointing to `localhost`, where dead_mans_switch_server will be installed too in runbots?

Could you tell me what value should it have? Thanks.

**Comment by hbrunn** [comment]
you can try that too, but I'm not sure that's guaranteed to work because there's no dependency between the two modules. Another issue is that tests don't use multithreading, so there's a chance the test justs deadlocks there.
But to try it anyways, use `http://localhost:$port/dead_mans_switch/alive`
