### ISSUE TITLE
[8.0][9.0] [base_name_search_improved] - impossible to search on  additional fields

### ISSUE THREAD

**Issue by aurelien-ideal** [OCA/server-tools#558]
Pb reproduced on the runbot on 8.0, and a fresh install of 9.0.

Configuration:
- base_name_search_improved installed + CRM
- res.partner updated with additional search field (i tried with phone, city, parent name, company, commercial entity)
- accessible on the runabout here : http://3154908-8-0-a4e5e5.runbot1.odoo-community.org/web?db=3154908-8-0-a4e5e5-all  (admin/admin)

What works:
- unordered word search : Agrolait, Michel Fletcher Dupont :> search on "dupont michel" works

What doesn't work:
- search on additional field of res.partner as phone, city,... 
- search on additional field one2many as parent name, company, commercial entity 

And the jaro (levenstein distance) doesn't seem to be activated.

This module is a must have, I hope we'll be able to fix it!

Thanks

![search](https://cloud.githubusercontent.com/assets/5859063/18745557/e0ba2636-80c2-11e6-801f-8d86f73df840.png)

**Comment by dreispt** [comment]
Hi @aurelien-ideal ,

Might there be some confusion? -
The `base_name_search_improved`has not been ported to 9.0 yet, and the levenstein distance is not an implemented feature.

**Comment by aurelien-ideal** [comment]
Hello @dreispt ,
Thanks for answering :)

Maybe there is confusion, but not on the version (as I wrote, I tested on both 8.0 and 9.0 as you can see BTW on the screenshots ) ;)

My big point is about name search fields that don't seems to work:
ex : entering "lucas think" never give me "Think Big Systems, Lucas Jones".....

"What doesn't work:
search on additional field of res.partner as phone, city,...
search on additional field one2many as parent name, company, commercial entity"

Le runbot a expiré, je viens d'en créer un nouveau : http://3270066-8-0-7b70cc.runbot1.odoo-community.org/web?debug=1#view_type=form&model=crm.lead&menu_id=183&action=192

![capture d ecran 2016-10-19 a 18 12 46](https://cloud.githubusercontent.com/assets/5859063/19527276/aebfeaf6-9627-11e6-97c0-0f34a50a0b69.png)

If you just can take 2min clicking the link, maybe I've missed something huge.... :)

Thanks a lot Daniel!!

**Comment by dreispt** [comment]
It might need a restart on the Odoo service to apply changes to the list of fields to search.
This is because that list is cached in the server, for best performance.

AFAICR it tries searching into each of the fields individually, but doesn't search across all fields at the same time. So "lucas bi" doesn't match Name, nor Parent Company, since one word is on the Name and the other is on the Parent...

On the other hand, the email contains both "lucas" and "bi", and it is searched by default, so it should have worked. This needs some tests on a local instance to figure what might be going on...

**Comment by pedrobaeza** [comment]
This bug doesn't seem to be correct, so I close.
