### ISSUE TITLE
[7.0] Sentry logger DSN warning

### ISSUE THREAD

**Issue by rousseldenis** [OCA/server-tools#627]
@gurneyalex Can you change DSN warning as runbot environnment changed ?

**Comment by gurneyalex** [comment]
@rousseldenis can you be more specific?

**Comment by rousseldenis** [comment]
@gurneyalex Ok. In sentry_logger module, you added a test if in runbot environment not to have warning. (see commit e386b31378544f1b7410c62dd4fbcbd81d5d7196)

As runbot environnment has changed, the test fails now.

**Comment by gurneyalex** [comment]
Hmmm I had forgotten about this.

@moylop260 do you know if there is an environment variable we can use as of now in the docker runbot builds to achieve the same result?

**Comment by moylop260** [comment]
I'll review it...

**Comment by lasley** [comment]
What about the [`SERVER_OPTIONS` created for Runbot to send in the log db](https://github.com/OCA/runbot-addons/blob/10.0/runbot_travis2docker/models/runbot_build.py#L120)? We'd at least only need to update the addon vs. further up the depends chain. In hindsight, I probably should have abstracted that a bit better so we could inherit and update.

**Comment by moylop260** [comment]
I got it
We need a environment variable called `OCA_CI` to detect a runbot build and skip this error from [here](https://github.com/OCA/server-tools/commit/e386b31378544f1b7410c62dd4fbcbd81d5d7196#diff-f7ec9d9cf4dfd5c128a322da6ee5ac11R59)

Currently we are using `OCA_RUNBOT` from our [base image](https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/~/dockerfile/) to detect runbot builds.

![vauxoo odoo 80 image shippable auto docker hub](https://cloud.githubusercontent.com/assets/6644187/20814147/20555a70-b7de-11e6-989c-712f81ad9691.png)


We have 2 options:
 1. Change server-tools to skip with `OCA_RUNBOT` instead of `OCA_CI`
 2. Add `OCA_CI` to base image

I don't know what is the better but I'll create a PR with the option 1

**Comment by moylop260** [comment]
@lasley 
Your idea is good to add dynamic values from `-e ENVIRONMENT_VARIABLE=value`
Am right?

For this case we need a simple flag like as
 - https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

![environment variables travis ci](https://cloud.githubusercontent.com/assets/6644187/20814507/7e7e7144-b7df-11e6-9e64-82dd53b892ed.png)

In order to detect a particular environment

**Comment by moylop260** [comment]
FYI https://github.com/OCA/server-tools/pull/632

**Comment by lasley** [comment]
Yup you're right @moylop260 - I wasn't fully understanding the issue.
