### ISSUE TITLE
Travis build for 9.0 is red!

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#689]
I [see](https://travis-ci.org/OCA/server-tools/jobs/188673110) problems in `html_image_url_extractor`, `html_text`, `auth_signup_verify_email` and `database_cleanup`.

**Comment by pedrobaeza** [comment]
The real error is on database_cleanup. The rest are triggered as part of the tests catching them.

**Comment by dreispt** [comment]
OK. I remember seeing some PRs related to that module...

**Comment by moylop260** [comment]
I fixed the last time `database_cleanup` test from https://github.com/OCA/server-tools/pull/612
Because odoo injected new errors: https://github.com/odoo/odoo/pull/13978/files#r88654967

Maybe a new error was injected again.

**Comment by Garamotte** [comment]
The fail seems to be expected, but the last merged PR was based on an old branch where tests didn't fail, see https://github.com/OCA/server-tools/pull/588#issuecomment-271899454

@gurneyalex : Would it be possible to test against `pull/XXX/merge` instead of (or in addition to) `pull/XXX/head` on Travis ?
`head` is the branch requested to be merged. `merge` is a branch where the requested branch is already merged into upstream.

**Comment by gurneyalex** [comment]
@sylvain-garancher I think this is the case already:

Quoting https://docs.travis-ci.com/user/pull-requests:

> Rather than test the commits that have been pushed to the branch the pull request is from, we test the merge between the origin and the upstream branch. To only build on push events, you can disable Build on Pull Requests from your repository settings.


But 


> Travis CI also currently doesn’t build pull requests when the upstream branch is updated. When this happens, GitHub will update the merge commit between the downstream and upstream branch, and send out a notifications. But Travis CI currently ignores this update, as it could lead to a large number of new builds on repositories with lots of pull requests and lots of updates on the upstream branches.

**Comment by lasley** [comment]
Is there something I can do to help here? I'm a bit unclear on what the error is, but if someone can maybe point me in a direction I'll see if I can fix our build. I'm abstracting from https://github.com/OCA/server-tools/issues/689#issuecomment-270938545 that maybe `database_cleanup` is deleting some resources that are required for later builds or something?

This seems like a recurrent problem, does anyone have thoughts on moving `datase_cleanup` into a build of its own? IIRC that's possible, and might be the best approach in order to avoid repeating test fixes? I'm just spitballing here though, I'm probably way off base.

**Comment by pedrobaeza** [comment]
We can indeed isolate this module. Its use is very special and should be uninstall when you finish to clean your installation, so :+1: for this.

**Comment by lasley** [comment]
🍏  from #719, closing
