### ISSUE TITLE
[10.0] Crash with base_suspend_security and sales_team

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/server-tools#708]
Hi guys,

I just found on issue with base_suspend_security in Odoo core.
In some cases, there is a crash [here](https://github.com/odoo/odoo/blob/10.0/addons/sales_team/models/crm_team.py#L22)

TypeError:` 'BaseSuspendSecurityUid' object has no attribute ```len```

This exception is raised from [this line](https://github.com/odoo/odoo/blob/10.0/odoo/osv/expression.py#L418) because the len function isn't override in BaseSuspendSecurityUid object.

So, I can imagine 2 solutions

* Override other operators/functions in ```BaseSuspendSecurityUid object```.
* Ask Odoo to replace ```self.env.uid``` by ```self.env.user.id``` in [this line](https://github.com/odoo/odoo/blob/10.0/addons/sales_team/models/crm_team.py#L17)

Personnaly, I find it cleaner to write ```self.env.user.id```

Any comment ?

Thanks,

Adrien

**Comment by lasley** [comment]
I think option 2 is the best personally, because I agree that `self.env.user.id` is cleaner. We have also run into some edge cases such as this one during the auth handling processes that were circumvented by preferring `self.env.user.id`. We have found no such edge cases for `self.env.user.id` to this point.

I wonder what the likelihood of the change being accepted into Odoo is. Having started in Odoo after new API existed, I always just figured I was lacking some history on the nuances between `self.env.uid` and `self.env.user.id`. I would assume Odoo SA knows the nuances though, so it makes me wonder if the `self.env.uid` was intentional.
