### ISSUE TITLE
mass_editing:  ValueError: Invalid domain term (u'model_id', u'in',.....

### ISSUE THREAD

**Issue by ki1022** [OCA/server-tools#806]
Trying to use mass_editing module for the first time.  After I choose a model and try to pick a field I get this error:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 820, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 842, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4669, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1509, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4215, in _search
    query = self._where_calc(args)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4016, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/usr/lib/python2.7/site-packages/odoo/osv/expression.py", line 1287, in to_sql
    q, p = self.__leaf_to_sql(leaf)
  File "/usr/lib/python2.7/site-packages/odoo/osv/expression.py", line 1212, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term (u'model_id', u'in', {u'model': u'product.supplierinfo', u'transient': False, u'name': u'Information about a product vendor', u'state': u'base'})

It happens no matter which model I choose.  Any help is appreciated, thank you!

**Comment by pedrobaeza** [comment]
Version?

**Comment by ki1022** [comment]
Sorry, 10 community.

**Comment by ki1022** [comment]
Version from here works ok:

https://github.com/JayVora-SerpentCS/MassEditing/

**Comment by neruok** [comment]
Also having this problem on odoo 10 enterprise.
I ran it locally in my dev environment with --log-sql --log-level debug.


[log.txt](https://github.com/OCA/server-tools/files/935492/log.txt)

I ran with these options because the problem might be sql related. I found that the function def __leaf_to_sql(self, eleaf) in odoo/odoo/osv/expression.py expects right to be a bool, list, or tuple and it's actually a dict. When changing the part that expects it to be a list or tuple to also accept a dict, it gave an sql error, here's the log from doing that.

[log2.txt](https://github.com/OCA/server-tools/files/935597/log2.txt)

**Comment by tafaRU** [comment]
We faced the same issue on 10 enterprise.

**Comment by raycollazo** [comment]
Having Same Issue with version 10 Enterprise

**Comment by jbchouinard** [comment]
Seeing same issue on v10 community and enterprise. I made PR#805 to try and fix it but my change broke something else.

The problem is that the domain definition in mass_editing_view.xml (line 48) uses a hardcoded hack to get the list of ids:

`domain="[('ttype', 'not in', ['reference', 'function']), ('model_id', 'in', model_ids and model_ids[0][2] or [])]"`

The structure of field objects in the frontend seems to have changed in v10. I checked, with the new structure, to get the list of ids you'd need to get [m[1] for m in model_ids] rather than model_ids[0][2], but list comprehensions are not supported by py.js, where this is evaluated.

https://github.com/JayVora-SerpentCS/MassEditing/

Looks likes SerpentCS's version should work. They added the field model_list, a Char field that saves the list of ids of model_ids as a string, and they use it directly in the domain.

`domain="[('ttype', 'not in', ['refenrence', 'function']), ('model_id', 'in', model_list)]"`

(Incidentally they introduced a new bug with this fix, the typo in 'refenrence' is new.)

Honestly I'm not too sure what the model_ids field is for in the first place, the onchange on model_id sets it equal to the list [model_id].

**Comment by rafaelbn** [comment]
Hello!! @ki1022 @neruok @tafaRU @raycollazo @jbchouinard 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- [x] https://github.com/OCA/server-tools/pull/848
- [x] https://github.com/OCA/server-tools/pull/849 
- [ ] https://github.com/OCA/server-tools/pull/786
- [ ] https://github.com/OCA/server-tools/pull/1209


Thanks

**Comment by rafaelbn** [comment]
One more fix in https://github.com/OCA/server-tools/pull/1209

**Comment by rafaelbn** [comment]
Ping @JayVora-SerpentCS , maybe could you help here?

**Comment by JayVora-SerpentCS** [comment]
I will make a new PR on OCA/server-ux as we fixed some and added new features too.

**Comment by JayVora-SerpentCS** [comment]
While the OCA code is merged, we have a temp copy at https://github.com/JayVora-SerpentCS/MassEditing/.

**Comment by rafaelbn** [comment]
Great @JayVora-SerpentCS !

By the wat https://github.com/OCA/server-tools/pull/848 and https://github.com/OCA/server-tools/pull/849 has been merged! :smiley:
