### ISSUE TITLE
[10.0] propose module to lock user during server maintenance

### ISSUE THREAD

**Issue by kittiu** [OCA/server-tools#828]
We want to contribute a module that allow blocking user (except admin) from logging in during server maintenance mode. (i.e., when admin want to do further configuration in the system).
It can be as simple as,

- Select all users, and click action-> Block user for server maintenance
- Users will be marked as "blocked"
- If he/she logging in, a warning message that user is blocked for server maintenance

Are there any similar addons exist and/or this module is good to be in OCA?

**Comment by dreispt** [comment]
:+1: 
AFAIK this doesn't exist yet.

**Comment by lasley** [comment]
Hmmm neat. I think we might need some sort of `base_maintainence` or something in order to define a maintenance mode for general usage. I proposed a similar mode in #790, which includes a maintenance mode page.

**Comment by kittiu** [comment]
@lasley I am still not very clear. I skim through #790 and it is about updating the modules, right? Are you suggesting this maintenance mode can be part of it?
note: I and @newtratip are very new to OCA. so, please feel free to suggest. :)

**Comment by dreispt** [comment]
Is this addressed by https://github.com/OCA/server-tools/pull/833 ?

**Comment by yajo** [comment]
An idea that always floated through my mind to achieve this is that under maintenance mode, every call to `write`, `delete` and `create` should be aborted.

An "easy" way to achieve this would be to require configuring a 2nd db user to be used in cursors under maintenance mode. Such user should have readonly access. A simple ribbon should appear while under that mode, both front and back ends.

Forbiding access to `/web/*` under maintenance is simply not enough because:

- If you are not going to be able to read data, it is way more easy to configure a beautiful 503 error page at proxy level for such path.
- Other controllers may still try to write to database (`/shop/checkout`, etc.).
- Connectors, API calls and cron jobs could still write.
