### ISSUE TITLE
[RFC] security_40x: Prevent Token Scraping

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#835]
This module will, at a minimum, track all 404 errors by IP & allow for the blocking of hosts based on the amount of errors that have been detected in a time period. This will effectively prevent token scraping, which is a very real concern given that there is sensitive data locked behind cryptographically insecure tokens (uuid4 strings). 

We currently use Fail2Ban for our clients to mitigate this concern, but this provides limited reporting capabilities. I'm also having a significant amount of trouble coming up with a Fail2Ban strategy in a Dockerized environment that doesn't violate the 1:1 app:container rule, that also doesn't have an unruly amount of access to my environment, and that is also scalable. I'm at zilch on that for the most part.

A forward looking goal here (TBD whether it's achievable) is to track all 40x errors generated by the system. These are key indicators to active attack attempts such as SQL injection, so are definitely also a concern. This might be pretty difficult though because I don't see a centralized mechanism for this outside of werkzeug itself. I'm pretty sure I don't want to go monkey patching werkzeug, so that's out I think.

We have a similar issue simply with the 404s, but I think that I can achieve this goal by overriding the `request.render` method to look for the `website.404` template. If that template's being generated, tally one for the error count. Pretty crappy solution though IMO - it seems like a giant band-aid.

We can nail most of our unauthorized errors via the `auth_brute_force` module, although it would be nice if we had an abstract way for all the 40x errors though.

Anyways, this is obviously theoretical at this point but I figured it would be best to get the conversation started because it's now come up in a few side conversations.

cc @LasLabs @Yajo @hbrunn

**Comment by hbrunn** [comment]
yes, very good one. So there are [two entry points](https://github.com/OCA/OCB/blob/10.0/odoo/service/wsgi_server.py#L169) for http requests in standard Odoo. The [root object](https://github.com/OCA/OCB/blob/10.0/odoo/http.py#L1282) should be relatively simple to wrap into something that intercepts exceptions/the response, for xmlrpc, I think [a bit deeper in the call tree](https://github.com/OCA/OCB/blob/10.0/odoo/http.py#L91) is a central function you can intercept. If I was an attacker, I'd try xmlrpc first, because the chance to find some unsecured function there is higher imho because many people are not aware that any non-underscore function with a model/multi signature is callable via this protocol. Then it's just hoping the function crashes often enough before the attacker has found out how to abuse it...

**Comment by lasley** [comment]
Oh nice I didn't think about explicitly catching the exceptions too, but that even provides more potential insight into what is happening other than simply the error codes. 

Thanks for the links, you saved me a bunch of time digging around.

**Comment by yajo** [comment]
Could you explain the hypothetical attack you want to mitigate?

**Comment by hbrunn** [comment]
@Yajo token guessing. For example when https://github.com/OCA/knowledge/pull/137 goes to production quality, I'll add code to detect too many wrong tokens per IP, and block them. This plugin could make checks per module superfluous, because it already takes care of the blocking

**Comment by lasley** [comment]
@Yajo I would also like to ward against other client generated errors, such as a high amount of 400s, which is an indicator of things like SQL injection attempts. Or 405s would be an example of someone attempting to probe XML-RPC for vulnerabilities.

We currently have our Fail2Ban blocking any client with more than 5 4xx errors in our watch interval, but need to move this out of Fail2Ban due to lack of a good Docker strategy.
