### ISSUE TITLE
ImportError: No module named server_environment_files

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#89]
I stumbled upon this when trying the scaffold command: https://github.com/odoo/odoo/issues/4034

Looking at the `server_environment` module, is has a dependency on a `server_environment_files` module that doesn't exist: https://github.com/OCA/server-tools/blob/8.0/server_environment/__openerp__.py#L25

Is this doomed to error or am I missing something?

**Comment by guewen** [comment]
It appears that the module has been renamed to `server_environment_files_sample` https://github.com/OCA/server-tools/tree/8.0/server_environment_files_sample.
However, `server_environment` really depends on a module `server_environment_files` that is usually specific to the customer because it contains the specific customization files (the supposed workflow is to copy `server_environment_files_sample` in a local path and rename it to `server_environment_files`). 
I can think of 2 solutions:
- rename `server_environment_files_sample` to `server_environment_files`
- remove the "hard" dependency in `server_environment` and handle the exceptions inside the module when `server_environment_files` is missing.

**Comment by pedrobaeza** [comment]
I think second one is better.

**Comment by dreispt** [comment]
I agree with Pedro.

**Comment by dreispt** [comment]
This is breaks my work environment, so I made #93, a quick fix that works for me.

**Comment by az-iB** [comment]
install python-ldap 2.4.19 it worked for me :
https://pypi.python.org/pypi/python-ldap/2.4.19#downloads

**Comment by dreispt** [comment]
I have python-ldap installed and am even using it. That can't be the cause.

**Comment by petrus-v** [comment]
Hi,

As this issue is open, I let a message here, `mail_environment` modue also has a dependency on a `server_environment_files` module that doesn't exist: https://github.com/OCA/server-tools/blob/8.0/mail_environment/__openerp__.py#L65

**Comment by gurneyalex** [comment]
note that this should no longer be breaking runbot builds.

**Comment by clonedagain** [comment]
It looks like this is fixed, can you confirm please?

**Comment by gurneyalex** [comment]
I do.

**Comment by KaloyanNaumov** [comment]
same applies to the "mail_environment" module. It's the same dependency definition.

**Comment by yajo** [comment]
Please see fix in #666
